### ISSUE TITLE
API: Enum type arguments invocation

### ISSUE THREAD

**Issue by eledhwen** [noleme/noleme-vault#65]
Make it possible to define pass `Enum` subtype arguments to constructor and methods in service definition files.

For instance, for a class `Foo` such that:

```java
package com.me;

public class Foo {
  private final FooType type;

  public Foo(FooType type) {
    this.type = type;
  }
}
```

and an enum `FooType`

```java
public enum FooType {
  ONE, TWO, THREE
}
```

We should be able to define an instance of `Foo` with the following service declaration:

```yml
services:

  foo_service:
    class: com.me.Foo
    constructor:
      - TWO
```
