### ISSUE TITLE
Scoped imports

### ISSUE THREAD

**Issue by eledhwen** [noleme/noleme-vault#7]
Imports are important to the current configuration model. The basic idea behind them is that configuration should be made of re-usable chunks, with variables as default parameters that can be overridden by a client project.

However, as it stands all imports happen in the same "scope", so it is not possible to re-use a set of services defined in a file several times.

So you can do this (assuming `mongodb_client.yml` declares a `mongodb.client` service):

Sample 1.
```yml
imports:
    - "path/to/mongodb_client.yml"

services:
    my_service:
        class: org.mycompany.MyClass
        constructor:
            - "@mongodb.client"
```

But if you need several clients with different configurations, it is currently not possible to do something like this:

Sample 2A.
```yml
imports:
    - "path/to/mongodb_client.yml"

services:
    my_service:
        class: org.mycompany.MyClass
        constructor:
            - "@variant_a.mongodb.client"

    my_other_service:
        class: org.mycompany.MyClass
        constructor:
            - "@variant_b.mongodb.client"
```

The idea for scoped imports would be to enable the developer to use a given configuration file as a pattern rather than a literal declaration. So the `Sample 2A` above could be declared somewhat like this: 

Sample 2B.
```yml
imports:
    - { from: "path/to/mongodb_client.yml", scope: "variant_a" }
    - { from: "path/to/mongodb_client.yml", scope: "variant_b" }

services:
    my_service:
        class: org.mycompany.MyClass
        constructor:
            - "@variant_a.mongodb.client"

    my_other_service:
        class: org.mycompany.MyClass
        constructor:
            - "@variant_b.mongodb.client"
```

Variables could maybe optionally be overridden from the import (assuming `mongodb_client.yml` declares a `mongodb.database` variable)?

Sample 3A.
```yml
imports:
    - from: "path/to/mongodb_client.yml"
      scope: "variant_a"
      variables:
          mongodb.database: "${DATABASE_A}"
    - from: "path/to/mongodb_client.yml"
      scope: "variant_b"
      variables:
          mongodb.database: "${DATABASE_B}"

services:
    my_service:
        class: org.mycompany.MyClass
        constructor:
            - "@variant_a.mongodb.client"

    my_other_service:
        class: org.mycompany.MyClass
        constructor:
            - "@variant_b.mongodb.client"
```

Or perhaps directly as a variable declaration:

Sample 3B.
```yml
imports:
    - { from: "path/to/mongodb_client.yml", scope: "variant_a" }
    - { from: "path/to/mongodb_client.yml", scope: "variant_b" }

variables:
    variant_a.mongodb.database: "${DATABASE_A}"
    variant_b.mongodb.database: "${DATABASE_B}"

services:
    my_service:
        class: org.mycompany.MyClass
        constructor:
            - "@variant_a.mongodb.client"

    my_other_service:
        class: org.mycompany.MyClass
        constructor:
            - "@variant_b.mongodb.client"
```

This could enable better re-use of configuration files, but also could make it possible for libraries to ship "blueprint" configuration files alongside their class definitions that can be used and scoped appropriately.

An important question is that of imports made by the template file.
How to interpret them? Can they always be scoped as well ?

**Comment by eledhwen** [comment]
An alternative solution could be leveraging the `services` block instead:

```yml
services:
    variant_a.mongodb.client:
        from: "path/to/mongodb_client.yml"
        blueprint: mongodb.client #identifier of the blueprint service
        variables:
            mongodb.database: "${DATABASE_A}"

    variant_b.mongodb.client:
        from: "path/to/mongodb_client.yml@mongodb.client" #maybe a variant?
        variables:
            mongodb.database: "${DATABASE_B}"

    my_service:
        class: org.mycompany.MyClass
        constructor:
            - "@variant_a.mongodb.client"

    my_other_service:
        class: org.mycompany.MyClass
        constructor:
            - "@variant_b.mongodb.client"
```

**Comment by eledhwen** [comment]
Additional ideas: dependency aliasing, allows the use of an externally defined service from within a scoped import.

```yml
services:
    variant_a.my_service:
        from: "path/to/service.yml"
        blueprint: my_service
        variables:
            my_parameter: "${WHATEVER_A}"
        aliases:
            my_dependency: @dependency_for_my_service

    variant_b.my_service:
        from: "path/to/service.yml"
        blueprint: my_service
        variables:
            my_parameter: "${WHATEVER_B}"
        aliases:
            my_dependency: @dependency_for_my_service

    dependency_for_my_service:
        class: org.mycompany.MyClass
```
